version: '3.3'
services:
  msa-api:
    image: shelleg/msa-api:config
    ports:
    - 8080:8080
    environment:
      NODE_ENV: "docker"
    depends_on:
    - redis
  redis:
    image: redis:5.0.7
    ports:
    - 6379:6379
